/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tables/{table_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Events
         * @description Every commit this client is entitled to, from where it left off and onward as they land.
         */
        get: operations["read_events_tables__table_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Journal
         * @description The table's full record, which opens to everyone once the host has called the game over.
         *
         *     The record reads the same to every client, so the seat behind the request settles nothing here.
         */
        get: operations["read_journal_tables__table_id__journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Layout
         * @description How this client lays the table out: the zones its seat holds and the moves it makes, and the
         *     shared table besides.
         *
         *     A layout answers for the match rather than for the position, so a client asks once as it joins.
         */
        get: operations["read_layout_tables__table_id__layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Move
         * @description Commit a seat's move to a table, answering with the sequence it landed at.
         */
        post: operations["submit_move_tables__table_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read View
         * @description The table as this client is entitled to see it, stamped with the sequence it stands at.
         */
        get: operations["read_view_tables__table_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionKind
         * @description The word an action carries as its tag, which is what tells one intent from another on the wire.
         *
         *     The tag is the discriminator of `AnyAction`, so a client sending a move names one of these and a layer
         *     reading a move back branches on it. Naming the vocabulary here lets anything that speaks about a kind of
         *     move — a presentation layer saying which gesture puts one on the table — hold a member rather than a
         *     string that happens to match.
         * @enum {string}
         */
        ActionKind: "play" | "take" | "give" | "reject" | "discard" | "declare";
        AnyAction: components["schemas"]["Play"] | components["schemas"]["Take"] | components["schemas"]["Give"] | components["schemas"]["Reject"] | components["schemas"]["Discard"] | components["schemas"]["Declare"];
        CardIndex: number;
        /**
         * Commit
         * @description The place a player points at to send the move a selection has armed.
         *
         *     `ZONE` sends it onto a zone of the table — the pile a card is exchanged with, the tray it is sealed in —
         *     which the gesture names. `SEAT` sends it onto another player, whom the move itself names.
         *
         *     Both are places on the table, so a move is committed by pointing at where it goes and a selection alone
         *     commits nothing. A game whose move carries a decision that no place on the table stands for — a bid, a
         *     trump chosen, a contract announced — gains a member here the day it is written.
         * @enum {string}
         */
        Commit: "zone" | "seat";
        /**
         * Declare
         * @description A claim a seat makes about cards it holds, for the rules to confirm or refuse.
         *
         *     `claim` is the game's own word for what is being claimed, which makes this the one intent carrying a word
         *     beside its cards: a claim states what the cards are held to be. `indices` names the cards it is made of,
         *     and an empty set makes it of the whole zone.
         */
        Declare: {
            /** Claim */
            claim: string;
            indices: components["schemas"]["Indices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "declare";
        };
        /** Discard */
        Discard: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "discard";
        };
        /**
         * Gesture
         * @description One kind of move as a player makes it: the zone the cards come out of, and the place clicked to send it.
         *
         *     A move is matched to its gesture by `kind` and `group`, which together are the whole of what an intent
         *     says beside the positions it names. `group` names the group this gesture is for, and reads None where the
         *     group tells no two gestures of that kind apart — a kind carrying no group at all reads None here.
         *
         *     `picked` is the zone the move's indices address, which is the zone a player selects cards in. It is a
         *     concrete zone because a layout is built for one observer, so the hand a move names is that observer's own.
         *     `target` is the zone clicked to commit, and reads None where the commit lands on a seat, since the move
         *     names the seat itself. `caption` states in words what the gesture does, for a player weighing it.
         */
        Gesture: {
            /** Caption */
            caption: string;
            commit: components["schemas"]["Commit"];
            /** Group */
            group: string | null;
            kind: components["schemas"]["ActionKind"];
            /** Picked */
            picked: string;
            /** Target */
            target: string | null;
        };
        /** Give */
        Give: {
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "give";
            /** Target Player */
            target_player: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        Indices: components["schemas"]["CardIndex"][];
        /**
         * Layout
         * @description Everything an interface needs to lay a game out for one seat, and nothing about how it looks.
         *
         *     A game states one of these per observer, so every zone id, seat and gesture in it is concrete and the
         *     interface resolves nothing: it draws the slots where they belong, matches the moves it is served to the
         *     gestures, reads the cursor through the readouts and captions the phase from `phases`. What is left over —
         *     the size of a card, the colour of a highlight, the moment a heap collapses — is the interface's own.
         *
         *     Every claim a layout makes about itself is checked as it is built, which leaves an interface free to trust
         *     it: one slot per zone, one slot per place in a region, one plaque per seat, one gesture per move, and every
         *     zone a gesture picks from or commits onto laid out as a slot the player can reach.
         */
        Layout: {
            /** Gestures */
            gestures: components["schemas"]["Gesture"][];
            /** Observer */
            observer: number | null;
            /** Phases */
            phases: {
                [key: string]: string;
            };
            /** Plaques */
            plaques: components["schemas"]["Plaque"][];
            /** Players */
            players: number;
            /** Readouts */
            readouts: components["schemas"]["Readout"][];
            /** Slots */
            slots: components["schemas"]["Slot"][];
            /** Title */
            title: string;
        };
        /**
         * Move
         * @description A seat's intent, before the rules have had a say.
         *
         *     Engine-initiated changes carry `Transaction.move = None`, which leaves every `Move` owned by a
         *     real seat.
         */
        Move: {
            action: components["schemas"]["AnyAction"];
            /** Player */
            player: number;
        };
        /**
         * MoveAccepted
         * @description The sequence a command was committed at, which the client quotes as `base_seq` for its next one.
         */
        MoveAccepted: {
            /** Seq */
            seq: number;
        };
        /**
         * MoveRequest
         * @description A command as a client sends it: the intent, the position it was built on, and a name for the try.
         *
         *     Repeating the key names the same attempt, so a client that retries a request it never saw answered
         *     lands its move once.
         */
        MoveRequest: {
            /** Base Seq */
            base_seq: number;
            /** Idempotency Key */
            idempotency_key: string;
            move: components["schemas"]["Move"];
        };
        NonEmptyIndices: components["schemas"]["CardIndex"][];
        /**
         * Plaque
         * @description One player as the whole table reads them: the seat, the name it plays under, and the zones it holds.
         *
         *     Every seat takes a plaque, the observer's own among them, so the standing reads across the table in one
         *     row. What the plaque shows beside the counts — the score, a game's own per-seat tally — comes from the
         *     readouts scoped to a seat, which leaves a plaque stating who is there rather than what is worth showing.
         */
        Plaque: {
            /** Counts */
            counts: components["schemas"]["Tally"][];
            /** Name */
            name: string;
            /** Seat */
            seat: number;
        };
        /** Play */
        Play: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "play";
        };
        /**
         * Readout
         * @description A field of the cursor shown to the player, under the word the game calls it by.
         *
         *     Every number and word an interface states about where play stands is one of these, so the score, the round
         *     in play and a game's own tallies all reach the screen by one route and no interface holds the name of a
         *     field a particular game declares. `field` names a field of the state the game is played with, and `scope`
         *     says whether that field speaks about the table or about each seat in turn.
         *
         *     `of` builds one against the state class that declares the field, which is what keeps the name honest.
         */
        Readout: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            scope: components["schemas"]["Scope"];
        };
        /**
         * Region
         * @description Where on the screen a zone is laid out, which is the whole of the geography a game states.
         *
         *     A `TABLE` zone is one the seats share and every one of them reads the same way: the pile dealt from, the
         *     stack laid on. A `SEAT` zone belongs to the observer the layout was built for, and holds the cards that
         *     observer acts with. Where each region sits on the page and how much of it a card takes belongs to the
         *     interface, which is why two names carry the whole of it.
         * @enum {string}
         */
        Region: "table" | "seat";
        /** Reject */
        Reject: {
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reject";
        };
        /**
         * Scope
         * @description Whom a field of the cursor speaks about.
         *
         *     A `TABLE` field holds one value for the whole table — the round in play, the phase, the trump — and reads
         *     in the line stating where play stands. A `SEAT` field holds one value per seat in seat order, as `points`
         *     does, and reads on each player's plaque.
         * @enum {string}
         */
        Scope: "table" | "seat";
        /**
         * Slot
         * @description One zone laid out: where it goes, how its cards lie against each other, and what it is called.
         *
         *     `place` orders the slots sharing a region, counting from the first. `counted` shows how many cards the
         *     zone holds, which is what a heap of backs has to say for itself and a hand of three states by lying
         *     there. Whether a slot may be selected from or committed onto follows from the gestures naming it, so a
         *     slot states where its cards are and leaves what they afford to the moves the rules admit.
         */
        Slot: {
            /** Counted */
            counted: boolean;
            /** Label */
            label: string;
            /** Place */
            place: number;
            region: components["schemas"]["Region"];
            spread: components["schemas"]["Spread"];
            /** Zone */
            zone: string;
        };
        /**
         * Spread
         * @description How the cards of one zone lie against each other.
         *
         *     `SLOT` is a single place, holding one card or standing empty. `STACK` is a heap, read by the card on top
         *     with the depth beneath it suggested. `FAN` overlaps cards so each stays partly readable, which is a hand
         *     held. `ROW` lays them side by side, each one whole.
         *
         *     A heap reads by its last card, since that is the end a game lays on. A heap dealt from its other end
         *     holds cards nobody reads — a face-down pile is a heap of backs, and reads alike from either end — so the
         *     field saying which end faces up arrives with the first game that deals readable cards from position zero.
         * @enum {string}
         */
        Spread: "slot" | "stack" | "fan" | "row";
        /** Take */
        Take: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "take";
        };
        /**
         * Tally
         * @description A count of one zone shown on a plaque, under the word the game calls that zone by.
         *
         *     A count is what a zone belonging to another seat says about itself: the cards are that seat's to read, and
         *     how many of them there are is the table's to know. So the zones a layout lays out as slots and the zones
         *     it tallies on a plaque divide by whose they are.
         */
        Tally: {
            /** Label */
            label: string;
            /** Zone */
            zone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_events_tables__table_id__events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_journal_tables__table_id__journal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_layout_tables__table_id__layout_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_move_tables__table_id__moves_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_view_tables__table_id__view_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
