/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Lobby
         * @description The whole lobby as the overseer reads it: every table, and the terms it is held under.
         */
        get: operations["read_lobby_admin_lobby_get"];
        /**
         * Settle Lobby
         * @description Settle the terms the lobby is held under: how many tables stand at once, and who may open one.
         */
        put: operations["settle_lobby_admin_lobby_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reap Tables
         * @description Clear away every table nobody is at that has sat too long, and answer with the names cleared.
         */
        post: operations["reap_tables_admin_reap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Table
         * @description Gather a table on the company's behalf, answering with the card that carries the code it admits on.
         */
        post: operations["post_table_admin_tables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tables/{table_id}/closing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Table
         * @description Break one table up whether it is gathering or in play, and answer with the lobby it leaves behind.
         */
        post: operations["close_table_admin_tables__table_id__closing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Offerings
         * @description Every game this host offers, and the tables and deck counts each of them is played with.
         *
         *     A page draws its whole choice from this, which is what leaves it holding the name of no game.
         */
        get: operations["read_offerings_offerings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Tables
         * @description The tables gathering here, which is what a page offers somebody who reached the server bare.
         *
         *     Read without a credential, as the offerings are: what admits a person is the code, so naming what is
         *     gathering costs a table nothing and saves the one who was handed no line from guessing.
         */
        get: operations["read_tables_tables_get"];
        put?: never;
        /**
         * Found
         * @description Gather a fresh table and seat its founder as the host, answering with the token they speak through.
         */
        post: operations["found_tables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/arrangements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arrange Zone
         * @description Lay a zone of this seat's own out in the order it asks for, answering with the sequence it landed at.
         *
         *     The seat comes off the credential rather than out of the request, so a client sorts the zones its own
         *     token holds and names no seat at all.
         */
        post: operations["arrange_zone_tables__table_id__arrangements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/choice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Settle Choice
         * @description Settle what the table plays, which every guest holding a say may do.
         */
        put: operations["settle_choice_tables__table_id__choice_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/closing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Gathering
         * @description Break the gathering up, which its host may call for, leaving the company a word on why.
         */
        post: operations["close_gathering_tables__table_id__closing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deal Table
         * @description Deal the table the company settled on, which opens it and ends the gathering.
         */
        post: operations["deal_table_tables__table_id__deal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Events
         * @description Every commit this client is entitled to, from where it left off and onward as they land.
         */
        get: operations["read_events_tables__table_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/gathering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Gathering
         * @description The gathering as this guest reads it: the company, what is settled, and where it stands.
         */
        get: operations["read_gathering_tables__table_id__gathering_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/gathering/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Attendance
         * @description How the gathering stands, again at every revision it reaches, until the table is dealt.
         */
        get: operations["read_attendance_tables__table_id__gathering_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/governance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Govern Table
         * @description Settle how the table is governed, which its host alone may do.
         */
        put: operations["govern_table_tables__table_id__governance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arrive
         * @description Admit one person on the code they offered, answering with the token they will speak through.
         */
        post: operations["arrive_tables__table_id__guests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Journal
         * @description The table's full record, which opens to everyone once the host has called the game over.
         *
         *     The record reads the same to every client, so the seat behind the request settles nothing here.
         */
        get: operations["read_journal_tables__table_id__journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Layout
         * @description How this client lays the table out: the zones its seat holds and the moves it makes, and the
         *     shared table besides.
         *
         *     A layout answers for the match rather than for the position, so a client asks once as it joins.
         */
        get: operations["read_layout_tables__table_id__layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Move
         * @description Commit a seat's move to a table, answering with the sequence it landed at.
         */
        post: operations["submit_move_tables__table_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Commit Ready
         * @description Commit to the settings as they stand, or take that commitment back, which every seated guest may do.
         */
        put: operations["commit_ready_tables__table_id__ready_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/seat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Claim Seat
         * @description Take a seat at the table, or stand up from the one held by naming none.
         */
        put: operations["claim_seat_tables__table_id__seat_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/tint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Take Tint
         * @description Take one of the company's tints, which every guest may do for their own.
         */
        put: operations["take_tint_tables__table_id__tint_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read View
         * @description The table as this client is entitled to see it, stamped with the sequence it stands at.
         */
        get: operations["read_view_tables__table_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionKind
         * @description The word an action carries as its tag, which is what tells one intent from another on the wire.
         *
         *     The tag is the discriminator of `AnyAction`, so a client sending a move names one of these and a layer
         *     reading a move back branches on it. Naming the vocabulary here lets anything that speaks about a kind of
         *     move — a presentation layer saying which gesture puts one on the table — hold a member rather than a
         *     string that happens to match.
         * @enum {string}
         */
        ActionKind: "pass" | "play" | "take" | "give" | "reject" | "discard" | "declare";
        /**
         * Admitted
         * @description What a guest is answered on arrival: the token they speak through, and the gathering they have joined.
         *
         *     The token is the whole of what this server knows of them. It rides the fragment of an address, which a
         *     browser sends to nobody, and reaches every endpoint in a header of its own.
         */
        Admitted: {
            gathering: components["schemas"]["GatheringView"];
            /** Token */
            token: string;
        };
        AnyAction: components["schemas"]["Pass"] | components["schemas"]["Play"] | components["schemas"]["Take"] | components["schemas"]["Give"] | components["schemas"]["Reject"] | components["schemas"]["Discard"] | components["schemas"]["Declare"];
        /**
         * ArrangementRequest
         * @description A seat laying a zone of its own out: the zone, the run it comes to lie in, and the position it was read at.
         *
         *     The seat asking is the one thing this leaves out, since the server reads it off the credential: a client
         *     states which of its zones it is sorting and never whose zone that is.
         *
         *     `order` names the positions the zone holds in the order they come to lie, so the first of them is the card
         *     that comes to lie first. Repeating the key names the same attempt, so a client that retries a request it
         *     never saw answered lands its order once.
         */
        ArrangementRequest: {
            /** Base Seq */
            base_seq: number;
            /** Idempotency Key */
            idempotency_key: string;
            order: components["schemas"]["Order"];
            /** Zone */
            zone: string;
        };
        /**
         * Arriving
         * @description One person arriving at a table: the code that admits them, and the name they will be read by.
         */
        Arriving: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * Award
         * @description Which end of a standing a match is won at.
         *
         *     A match is decided on `points`, and whether the seat holding the most of them or the fewest takes it is a rule
         *     of the game: one scoring what a seat wins reads `HIGHEST`, and one scoring what it is caught with reads
         *     `LOWEST`. It stands beside the tally it reads, so the rules settling a match on a lead and the interface
         *     naming the seat that took it ask the same question of the same standing.
         * @enum {string}
         */
        Award: "highest" | "lowest";
        /**
         * Capacity
         * @description The tables a game is played at: the fewest seats it needs and the most it holds.
         *
         *     A game states its seating as a declaration rather than a check, so the range a reader looks for stands
         *     beside the vocabulary the game is played with, and the engine holds every table it opens to it:
         *
         *         capacity: ClassVar[Capacity] = Capacity(least=2, most=5)
         *
         *     A game played at one size states that size as both. A game bounded by the cards it deals states the
         *     table its deck reaches, since a seating range is something a game has settled rather than discovered.
         */
        Capacity: {
            /** Least */
            least: number;
            /** Most */
            most: number;
        };
        CardIndex: number;
        /**
         * Choice
         * @description What a gathering has settled to play: the game, the table, the decks it is dealt from, and where it ends.
         *
         *     This is what a table is opened with once the deal is called for, and every field of it is something the
         *     company settles rather than something the host fixes. The game is named as a plain word for the same reason
         *     a phase is: the vocabulary belongs to whatever holds the rules, and the adapter reads a name it confirms
         *     against what the host says it offers.
         *
         *     `cues` is the one field the rules read nothing of: whether the table lights the cards a seat may play, which
         *     a company settles like the rest and an advanced one turns off. It travels with the choice so a page settles
         *     it beside the game and it reaches the table the deal opens, where the layout carries it to every seat.
         */
        Choice: {
            conclusion: components["schemas"]["Conclusion"];
            /**
             * Cues
             * @default true
             */
            cues: boolean;
            /** Decks */
            decks: number;
            /** Game */
            game: string;
            /** Players */
            players: number;
        };
        /**
         * Choosing
         * @description A guest settling what the table plays.
         */
        Choosing: {
            /** Base Revision */
            base_revision: number;
            choice: components["schemas"]["Choice"];
        };
        /**
         * Claiming
         * @description A guest taking a seat, or standing up from the one they hold by naming none.
         */
        Claiming: {
            /** Base Revision */
            base_revision: number;
            /** Seat */
            seat: number | null;
        };
        /**
         * Closing
         * @description Breaking a table up, with a word for the company on why, which the host or an admin may call for.
         */
        Closing: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * CommandAccepted
         * @description The sequence a command was committed at, which the table stands one commit past.
         *
         *     A client holding this commit stands at `seq + 1` commits, and that count is what its next command quotes
         *     as `base_seq`. A move and an arrangement are answered alike, since what either of them leaves behind is
         *     one commit in the record every seat reads.
         */
        CommandAccepted: {
            /** Seq */
            seq: number;
        };
        /**
         * Commit
         * @description How a player sends the move a selection has armed.
         *
         *     `ZONE` sends it onto a zone of the table — the pile a card is exchanged with, the tray it is sealed in —
         *     which the gesture names. `SEAT` sends it onto another player, whom the move itself names. Both are places
         *     on the table, so a move naming cards is committed by pointing at where those cards go, and a selection
         *     alone commits nothing.
         *
         *     `WORD` is the third answer, for a move a place on the table stands for none of: a turn given up names no
         *     card and no destination, so a seat says it rather than points at it. A gesture committing this way names
         *     no target, and an interface draws it as somewhere to press rather than as a place cards travel to.
         *
         *     A game whose move carries a decision of its own — a bid, a trump chosen, a contract announced — is said
         *     the same way, which is what `Declare` is waiting on (`architecture.md` §5.3).
         * @enum {string}
         */
        Commit: "zone" | "seat" | "word";
        /**
         * Conclusion
         * @description How long a match runs: the clauses it ends on, of which a match states at least one.
         *
         *     A match ends on a count of rounds played, on a score some seat reaches, or on a lead one seat opens over the
         *     next best, and a table states whichever of those the match it opens is played to. Several stated together end
         *     it on the first of them the standing meets, which is how a match runs to five hundred points or ten rounds,
         *     whichever arrives first.
         *
         *     | clause | ends the match once |
         *     |---|---|
         *     | `rounds` | that many rounds have been played |
         *     | `target` | some seat holds that score, whether reaching it wins the match or loses it |
         *     | `lead` | the seat at the winning end of the standing leads the next best by that margin |
         *
         *     This is what a table is opened with, and the clauses it states are stamped onto the cursor the table opens on,
         *     so a replayed position describes the ending it was always running to. `RoundState` carries them there and
         *     reads them as `concluded`.
         */
        Conclusion: {
            /** Lead */
            lead?: number | null;
            /** Rounds */
            rounds?: number | null;
            /** Target */
            target?: number | null;
        };
        /**
         * Creation
         * @description Who may gather a table here: everyone, the overseer alone, or everyone until the overseer says otherwise.
         *
         *     A friendly host lets the company gather its own tables, a guarded one keeps the opening of them to whoever
         *     runs it, and a hybrid one starts open and closes on a word: the overseer settling it to `admin-only` is what
         *     turns a run from the first into the second without a restart.
         * @enum {string}
         */
        Creation: "self-serve" | "admin-only" | "hybrid";
        /**
         * Dealing
         * @description A guest calling for the deal, which opens the table and ends the gathering.
         */
        Dealing: {
            /** Base Revision */
            base_revision: number;
        };
        /**
         * Declare
         * @description A claim a seat makes about cards it holds, for the rules to confirm or refuse.
         *
         *     `claim` is the game's own word for what is being claimed, which makes this the one intent carrying a word
         *     beside its cards: a claim states what the cards are held to be. `indices` names the cards it is made of,
         *     and an empty set makes it of the whole zone.
         */
        Declare: {
            /** Claim */
            claim: string;
            indices: components["schemas"]["Indices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "declare";
        };
        /** Discard */
        Discard: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "discard";
        };
        /**
         * Founding
         * @description Gathering a new table: the name it answers under, the name its host arrives under, and what it opens on.
         *
         *     The host names the table and themselves at once, since founding a table is arriving at it: the code is drawn
         *     for them and handed back, and the token minted seats the host the way an arrival seats any guest.
         */
        Founding: {
            choice: components["schemas"]["Choice"];
            /** Name */
            name: string;
            /** Table */
            table: string;
        };
        /**
         * GatheringView
         * @description A gathering as one of its guests reads it: the company, what is settled, and where the gathering stands.
         *
         *     `revision` counts the changes the gathering has been through, and a command quotes the one it was built on
         *     the way a move quotes a sequence, so two guests settling the choice at once leaves the second told rather
         *     than overruled. `dealt` turns true once, which is what carries every page from the gathering to the table.
         *
         *     `democratic` is how the table is governed: true where every seated guest settles what is played, and false
         *     where the say is the host's alone. `closed` turns true when the gathering is broken up before it is dealt,
         *     which ends it the way the deal does but carries the company nowhere.
         */
        GatheringView: {
            choice: components["schemas"]["Choice"];
            /** Closed */
            closed: boolean;
            /** Code */
            code: string;
            /** Company */
            company: components["schemas"]["Guest"][];
            /** Dealt */
            dealt: boolean;
            /** Democratic */
            democratic: boolean;
            /** Mine */
            mine: string;
            /** Reason */
            reason: string | null;
            /** Revision */
            revision: number;
            /** Table */
            table: string;
        };
        /**
         * Gesture
         * @description One kind of move as a player makes it: the zone the cards come out of, and how the move is sent.
         *
         *     A move is matched to its gesture by `kind` and `group`, which together are the whole of what an intent
         *     says beside the positions it names. `group` names the group this gesture is for, and reads None where the
         *     group tells no two gestures of that kind apart — a kind carrying no group at all reads None here.
         *
         *     `picked` is the zone the move's indices address, which is the zone a player selects cards in. It is a
         *     concrete zone because a layout is built for one observer, so the hand a move names is that observer's own.
         *     It reads None for a move naming no card at all, which leaves a player nothing to select and an interface
         *     no zone to hold open: a pass is made in no zone, so it picks in none.
         *
         *     `commit` is how the move leaves, and `target` the zone it lands on, which reads None for the two commits
         *     naming no zone — a seat commit takes its seat from the move, and a word is said rather than pointed at.
         *     `caption` states in words what the gesture does, for a player weighing it.
         */
        Gesture: {
            /** Caption */
            caption: string;
            commit: components["schemas"]["Commit"];
            /** Group */
            group: string | null;
            kind: components["schemas"]["ActionKind"];
            /** Picked */
            picked: string | null;
            /** Target */
            target: string | null;
        };
        /** Give */
        Give: {
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "give";
            /** Target Player */
            target_player: number;
        };
        /**
         * Governing
         * @description The host settling how the table is governed: democratically, or by the host's own say alone.
         */
        Governing: {
            /** Base Revision */
            base_revision: number;
            /** Democratic */
            democratic: boolean;
        };
        /**
         * Guest
         * @description One person at a gathering as the company reads them: the name, the tint, the seat, and whether they are here.
         *
         *     The name is what a guest arrived under and the whole of their identity at the table. The tint is what tells
         *     them apart from the rest of the company at a glance, and no two guests hold one. The seat is the one they
         *     have taken, and none while they are standing. Presence follows the stream a page holds open, so the company
         *     reads as the room does.
         *
         *     `ready` is whether the guest has committed to the settings as they stand, which only a seated guest may do
         *     and any change to what is played or who plays it takes back. `host` marks the guest who gathered the table,
         *     whose say governs it while it is settled host by host rather than company-wide.
         */
        Guest: {
            /** Host */
            host: boolean;
            /** Name */
            name: string;
            /** Present */
            present: boolean;
            /** Ready */
            ready: boolean;
            /** Seat */
            seat: number | null;
            tint: components["schemas"]["Tint"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        Indices: components["schemas"]["CardIndex"][];
        /**
         * Interlude
         * @description A pause in play, held open for the players to read what the table has just come to.
         *
         *     A boundary settles in a burst — the round scored into the standing, the cards gathered, the next hand dealt —
         *     so a player watching the screen alone reads a round giving way to a fresh one with nothing said about what it
         *     came to. A phase named as an interlude is one the interface stops at and reads out: `ROUND` is a round closed
         *     with the next still to open, and `MATCH` is a match played out.
         *
         *     Which phases those are is a game's to state, since a game names the phases of its own rounds, and a match
         *     played through `cardwork.rounds` states the pair `presets.match_interludes` holds.
         * @enum {string}
         */
        Interlude: "round" | "match";
        /**
         * Layout
         * @description Everything an interface needs to lay a game out for one seat, and nothing about how it looks.
         *
         *     A game states one of these per observer, so every zone id, seat and gesture in it is concrete and the
         *     interface resolves nothing: it draws the slots where they belong, matches the moves it is served to the
         *     gestures, reads the cursor through the readouts and captions the phase from `phases`. What is left over —
         *     the size of a card, the colour of a highlight, the moment a heap collapses — is the interface's own.
         *
         *     The line runs between which thing is meant and what it looks like: a plaque states which of eight tints a
         *     player is told apart by, and what that tint draws as belongs to the interface, exactly as a spread states
         *     how cards lie against each other and where they lie belongs to the page.
         *
         *     Every claim a layout makes about itself is checked as it is built, which leaves an interface free to trust
         *     it: one slot per zone, a slot belonging to a seat of the table or to the table itself, one slot per place
         *     among the slots of one owner, one plaque per seat, one gesture per move, every zone a gesture names laid
         *     out as a slot the player can reach, and a phase play pauses at captioned like any other.
         */
        Layout: {
            award: components["schemas"]["Award"];
            /**
             * Cues
             * @default true
             */
            cues: boolean;
            /** Gestures */
            gestures: components["schemas"]["Gesture"][];
            /** Interludes */
            interludes: {
                [key: string]: components["schemas"]["Interlude"];
            };
            /** Observer */
            observer: number | null;
            /** Phases */
            phases: {
                [key: string]: string;
            };
            /** Plaques */
            plaques: components["schemas"]["Plaque"][];
            /** Players */
            players: number;
            /** Readouts */
            readouts: components["schemas"]["Readout"][];
            /** Slots */
            slots: components["schemas"]["Slot"][];
            /** Title */
            title: string;
        };
        /**
         * LobbySetting
         * @description A change to the terms the lobby is held under, which the overseer settles a field at a time.
         */
        LobbySetting: {
            /** Capacity */
            capacity?: number | null;
            creation?: components["schemas"]["Creation"] | null;
        };
        /**
         * LobbyView
         * @description The lobby as the overseer reads it: every table it holds, and the terms it holds them under.
         */
        LobbyView: {
            /** Capacity */
            capacity: number;
            /** Census */
            census: number;
            creation: components["schemas"]["Creation"];
            /** Tables */
            tables: components["schemas"]["TableCard"][];
        };
        /**
         * Move
         * @description A seat's intent, before the rules have had a say.
         *
         *     Engine-initiated changes carry `Transaction.move = None`, which leaves every `Move` owned by a
         *     real seat.
         */
        Move: {
            action: components["schemas"]["AnyAction"];
            /** Player */
            player: number;
        };
        /**
         * MoveRequest
         * @description A command as a client sends it: the intent, the position it was built on, and a name for the try.
         *
         *     Repeating the key names the same attempt, so a client that retries a request it never saw answered
         *     lands its move once.
         */
        MoveRequest: {
            /** Base Seq */
            base_seq: number;
            /** Idempotency Key */
            idempotency_key: string;
            move: components["schemas"]["Move"];
        };
        NonEmptyIndices: components["schemas"]["CardIndex"][];
        /**
         * Offering
         * @description One game a host offers, the tables it seats and the deck counts it is dealt from.
         *
         *     A client draws every control of a gathering from these, so a page settles a game while holding the name of
         *     none: what may be chosen is what the host says it offers, and a choice is confirmed against the same answer
         *     before a card is dealt.
         */
        Offering: {
            /** Decks */
            decks: number[];
            /** Game */
            game: string;
            seats: components["schemas"]["Capacity"];
            /** Title */
            title: string;
        };
        Order: components["schemas"]["CardIndex"][];
        /**
         * Pass
         * @description A turn given up, which is the one intent naming no card at all.
         *
         *     A seat with nothing it may play, or nothing it will, says so with this and the turn carries on to the next.
         *     The word is the whole of the move: the cards lie where they lay and the rules read the pass itself, which
         *     is what `indices_of` answers with an empty run for.
         */
        Pass: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pass";
        };
        /**
         * Plaque
         * @description One player as the whole table reads them: the seat, the name and tint it plays under, and the zones it holds.
         *
         *     Every seat takes a plaque, the observer's own among them, so the standing reads across the table in one
         *     row. What the plaque shows beside the counts — the score, a game's own per-seat tally — comes from the
         *     readouts scoped to a seat, which leaves a plaque stating who is there rather than what is worth showing.
         *
         *     A seat is named by where it sits and plays under no tint until a host holds one for it, since who is at a
         *     seat and how a company tells itself apart are both settled above the rules.
         */
        Plaque: {
            /** Counts */
            counts: components["schemas"]["Tally"][];
            /** Name */
            name: string;
            /** Seat */
            seat: number;
            tint: components["schemas"]["Tint"] | null;
        };
        /** Play */
        Play: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "play";
        };
        /**
         * Posting
         * @description The overseer gathering a table on the company's behalf: the name it answers under, and what it opens on.
         */
        Posting: {
            choice: components["schemas"]["Choice"];
            /** Table */
            table: string;
        };
        /**
         * Readout
         * @description A field of the cursor shown to the player, under the word the game calls it by.
         *
         *     Every number and word an interface states about where play stands is one of these, so the score, the round
         *     in play and a game's own tallies all reach the screen by one route and no interface holds the name of a
         *     field a particular game declares. `field` names a field of the state the game is played with, and `scope`
         *     says whether that field speaks about the table or about each seat in turn.
         *
         *     `of` builds one against the state class that declares the field, which is what keeps the name honest.
         */
        Readout: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            scope: components["schemas"]["Scope"];
        };
        /**
         * Readying
         * @description A seated guest committing to the settings as they stand, or taking that commitment back.
         *
         *     Readiness is the guest's own word that the choice may be dealt, so it names where the gathering stood when
         *     the word was given: a setting changing under it is what takes the word back, and a stale one is refused
         *     rather than read as an answer to a question that has moved on.
         */
        Readying: {
            /** Base Revision */
            base_revision: number;
            /** Ready */
            ready: boolean;
        };
        /** Reject */
        Reject: {
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reject";
        };
        /**
         * Scope
         * @description Whom a field of the cursor speaks about.
         *
         *     A `TABLE` field holds one value for the whole table — the round in play, the phase, the trump — and reads
         *     in the line stating where play stands. A `SEAT` field holds one value per seat in seat order, as `points`
         *     does, and reads on each player's plaque.
         * @enum {string}
         */
        Scope: "table" | "seat";
        /**
         * Slot
         * @description One zone laid out: whose it is, how its cards lie against each other, and what it is called.
         *
         *     `seat` names the owner of the zone, and None a zone the seats share and every one of them reads the same
         *     way: the pile dealt from, the stack laid on. Where an owner's zones go on the page is the interface's own —
         *     the seat reading the layout holds one place, each of the others another, and the shared zones the middle —
         *     which is why one number carries the whole of the geography a game states.
         *
         *     `place` orders the slots one owner holds, read from the lowest upwards. `counted` shows how many cards the
         *     zone holds, which is what a heap of backs has to say for itself and a hand of three states by lying there.
         *     Whether a slot may be selected from or committed onto follows from the gestures naming it, so a slot states
         *     where its cards are and leaves what they afford to the moves the rules admit.
         */
        Slot: {
            /** Counted */
            counted: boolean;
            /** Label */
            label: string;
            /** Place */
            place: number;
            /** Seat */
            seat: number | null;
            spread: components["schemas"]["Spread"];
            /** Zone */
            zone: string;
        };
        /**
         * Spread
         * @description How the cards of one zone lie against each other.
         *
         *     `SLOT` is a single place, holding one card or standing empty. `STACK` is a heap, read by the card on top
         *     with the depth beneath it suggested. `FAN` overlaps cards so each stays partly readable, which is a hand
         *     held. `ROW` lays them side by side, each one whole.
         *
         *     A heap reads by its last card, since that is the end a game lays on. A heap dealt from its other end
         *     holds cards nobody reads — a face-down pile is a heap of backs, and reads alike from either end — so the
         *     field saying which end faces up arrives with the first game that deals readable cards from position zero.
         * @enum {string}
         */
        Spread: "slot" | "stack" | "fan" | "row";
        /**
         * TableCard
         * @description One table as the overseer reads it: where it stands, how large, who is at it, and how long it has idled.
         *
         *     A gathering and a table in service read the same shape here, so the panel lists both in one hand: a
         *     gathering carries the code it admits on and the company reading it, and a table in play carries neither,
         *     since its company was carried to it and its cards are the seats' own.
         */
        TableCard: {
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Code */
            code?: string | null;
            /** Democratic */
            democratic?: boolean | null;
            /** Host */
            host?: string | null;
            /** Idle */
            idle: number;
            /** Phase */
            phase: string;
            /** Present */
            present?: number | null;
            /** Seats */
            seats: number;
            /** Table */
            table: string;
        };
        /** Take */
        Take: {
            /** Group */
            group: string;
            indices: components["schemas"]["NonEmptyIndices"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "take";
        };
        /**
         * Tally
         * @description A count of one zone shown on a plaque, under the word the game calls that zone by.
         *
         *     A count is what a zone belonging to another seat says about itself: the cards are that seat's to read, and
         *     how many of them there are is the table's to know. So the zones a layout lays out as slots and the zones
         *     it tallies on a plaque divide by whose they are.
         */
        Tally: {
            /** Label */
            label: string;
            /** Zone */
            zone: string;
        };
        /**
         * Tint
         * @description One player as the table tells them apart from the next, beside the name they play under.
         *
         *     A seat is read by its name, and a company round one table reads faster for a mark that carries at a
         *     glance: the plaque, the cards and the place a player holds all say the same one of these. Which player
         *     holds which is settled where a company gathers, and a table stands under as many tints as it seats.
         *
         *     What a tint comes to on a screen is the interface's, as the colour of a highlight is: these name eight
         *     players apart and say nothing about how any of them is drawn.
         * @enum {string}
         */
        Tint: "rose" | "coral" | "amber" | "lemon" | "teal" | "azure" | "indigo" | "violet";
        /**
         * Tinting
         * @description A guest taking one of the company's tints, which is the mark the table tells them apart by.
         */
        Tinting: {
            /** Base Revision */
            base_revision: number;
            tint: components["schemas"]["Tint"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_lobby_admin_lobby_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_lobby_admin_lobby_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LobbySetting"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reap_tables_admin_reap_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_table_admin_tables_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Posting"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_table_admin_tables__table_id__closing_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Closing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_offerings_offerings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offering"][];
                };
            };
        };
    };
    read_tables_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    found_tables_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Founding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admitted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arrange_zone_tables__table_id__arrangements_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArrangementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_choice_tables__table_id__choice_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Choosing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_gathering_tables__table_id__closing_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Closing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_table_tables__table_id__deal_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dealing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_events_tables__table_id__events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_gathering_tables__table_id__gathering_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_attendance_tables__table_id__gathering_events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    govern_table_tables__table_id__governance_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Governing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arrive_tables__table_id__guests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Arriving"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admitted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_journal_tables__table_id__journal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_layout_tables__table_id__layout_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_move_tables__table_id__moves_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_ready_tables__table_id__ready_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Readying"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_seat_tables__table_id__seat_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Claiming"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_tint_tables__table_id__tint_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tinting"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_view_tables__table_id__view_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Seat-Token"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
