from typing import Final

from cardwork.cards.card import Card
from cardwork.cards.joker import Joker
from cardwork.cards.rank import Rank
from cardwork.cards.suit import Suit

TWO_OF_SPADES: Final[Card] = Card(rank=Rank.TWO, suit=Suit.SPADE)
THREE_OF_SPADES: Final[Card] = Card(rank=Rank.THREE, suit=Suit.SPADE)
FOUR_OF_SPADES: Final[Card] = Card(rank=Rank.FOUR, suit=Suit.SPADE)
FIVE_OF_SPADES: Final[Card] = Card(rank=Rank.FIVE, suit=Suit.SPADE)
SIX_OF_SPADES: Final[Card] = Card(rank=Rank.SIX, suit=Suit.SPADE)
SEVEN_OF_SPADES: Final[Card] = Card(rank=Rank.SEVEN, suit=Suit.SPADE)
EIGHT_OF_SPADES: Final[Card] = Card(rank=Rank.EIGHT, suit=Suit.SPADE)
NINE_OF_SPADES: Final[Card] = Card(rank=Rank.NINE, suit=Suit.SPADE)
TEN_OF_SPADES: Final[Card] = Card(rank=Rank.TEN, suit=Suit.SPADE)
JACK_OF_SPADES: Final[Card] = Card(rank=Rank.JACK, suit=Suit.SPADE)
QUEEN_OF_SPADES: Final[Card] = Card(rank=Rank.QUEEN, suit=Suit.SPADE)
KING_OF_SPADES: Final[Card] = Card(rank=Rank.KING, suit=Suit.SPADE)
ACE_OF_SPADES: Final[Card] = Card(rank=Rank.ACE, suit=Suit.SPADE)

TWO_OF_HEARTS: Final[Card] = Card(rank=Rank.TWO, suit=Suit.HEART)
THREE_OF_HEARTS: Final[Card] = Card(rank=Rank.THREE, suit=Suit.HEART)
FOUR_OF_HEARTS: Final[Card] = Card(rank=Rank.FOUR, suit=Suit.HEART)
FIVE_OF_HEARTS: Final[Card] = Card(rank=Rank.FIVE, suit=Suit.HEART)
SIX_OF_HEARTS: Final[Card] = Card(rank=Rank.SIX, suit=Suit.HEART)
SEVEN_OF_HEARTS: Final[Card] = Card(rank=Rank.SEVEN, suit=Suit.HEART)
EIGHT_OF_HEARTS: Final[Card] = Card(rank=Rank.EIGHT, suit=Suit.HEART)
NINE_OF_HEARTS: Final[Card] = Card(rank=Rank.NINE, suit=Suit.HEART)
TEN_OF_HEARTS: Final[Card] = Card(rank=Rank.TEN, suit=Suit.HEART)
JACK_OF_HEARTS: Final[Card] = Card(rank=Rank.JACK, suit=Suit.HEART)
QUEEN_OF_HEARTS: Final[Card] = Card(rank=Rank.QUEEN, suit=Suit.HEART)
KING_OF_HEARTS: Final[Card] = Card(rank=Rank.KING, suit=Suit.HEART)
ACE_OF_HEARTS: Final[Card] = Card(rank=Rank.ACE, suit=Suit.HEART)

TWO_OF_CLUBS: Final[Card] = Card(rank=Rank.TWO, suit=Suit.CLUB)
THREE_OF_CLUBS: Final[Card] = Card(rank=Rank.THREE, suit=Suit.CLUB)
FOUR_OF_CLUBS: Final[Card] = Card(rank=Rank.FOUR, suit=Suit.CLUB)
FIVE_OF_CLUBS: Final[Card] = Card(rank=Rank.FIVE, suit=Suit.CLUB)
SIX_OF_CLUBS: Final[Card] = Card(rank=Rank.SIX, suit=Suit.CLUB)
SEVEN_OF_CLUBS: Final[Card] = Card(rank=Rank.SEVEN, suit=Suit.CLUB)
EIGHT_OF_CLUBS: Final[Card] = Card(rank=Rank.EIGHT, suit=Suit.CLUB)
NINE_OF_CLUBS: Final[Card] = Card(rank=Rank.NINE, suit=Suit.CLUB)
TEN_OF_CLUBS: Final[Card] = Card(rank=Rank.TEN, suit=Suit.CLUB)
JACK_OF_CLUBS: Final[Card] = Card(rank=Rank.JACK, suit=Suit.CLUB)
QUEEN_OF_CLUBS: Final[Card] = Card(rank=Rank.QUEEN, suit=Suit.CLUB)
KING_OF_CLUBS: Final[Card] = Card(rank=Rank.KING, suit=Suit.CLUB)
ACE_OF_CLUBS: Final[Card] = Card(rank=Rank.ACE, suit=Suit.CLUB)

TWO_OF_DIAMONDS: Final[Card] = Card(rank=Rank.TWO, suit=Suit.DIAMOND)
THREE_OF_DIAMONDS: Final[Card] = Card(rank=Rank.THREE, suit=Suit.DIAMOND)
FOUR_OF_DIAMONDS: Final[Card] = Card(rank=Rank.FOUR, suit=Suit.DIAMOND)
FIVE_OF_DIAMONDS: Final[Card] = Card(rank=Rank.FIVE, suit=Suit.DIAMOND)
SIX_OF_DIAMONDS: Final[Card] = Card(rank=Rank.SIX, suit=Suit.DIAMOND)
SEVEN_OF_DIAMONDS: Final[Card] = Card(rank=Rank.SEVEN, suit=Suit.DIAMOND)
EIGHT_OF_DIAMONDS: Final[Card] = Card(rank=Rank.EIGHT, suit=Suit.DIAMOND)
NINE_OF_DIAMONDS: Final[Card] = Card(rank=Rank.NINE, suit=Suit.DIAMOND)
TEN_OF_DIAMONDS: Final[Card] = Card(rank=Rank.TEN, suit=Suit.DIAMOND)
JACK_OF_DIAMONDS: Final[Card] = Card(rank=Rank.JACK, suit=Suit.DIAMOND)
QUEEN_OF_DIAMONDS: Final[Card] = Card(rank=Rank.QUEEN, suit=Suit.DIAMOND)
KING_OF_DIAMONDS: Final[Card] = Card(rank=Rank.KING, suit=Suit.DIAMOND)
ACE_OF_DIAMONDS: Final[Card] = Card(rank=Rank.ACE, suit=Suit.DIAMOND)

BLACK_JOKER: Final[Joker] = Joker(red=False)
RED_JOKER: Final[Joker] = Joker(red=True)
